version: "3.9"
   
services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: django_auth_demo-web-container
    volumes:
      - ../:/django_auth_demo_stuff
      - ../DBs:/django_auth_demo_stuff/DBs
      - ../logs:/django_auth_demo_stuff/logs
      - .:/django_auth_demo_stuff/code
    ports:
      - "8000:8000"

    environment:
      - DJ_TMPLT32__ENV_SETTINGS_PATH=config/settings_localdev_env.sh

    env_file: ./config/settings_localdev_env.sh

    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
